# ref: https://stackoverflow.com/questions/35110123/travis-ci-with-c14-and-linux
language: generic
script: make

matrix:
  include:
    - os: linux
      dist: trusty    
      env: COMPILER_NAME=g++ CXX=g++-7 ARCH=x86
      addons:
        apt:
          packages:
            - g++-7-multilib
            - linux-libc-dev:i386
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      dist: trusty
      env: COMPILER_NAME=g++ CXX=g++-7 ARCH=x64
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      dist: trusty
      env: COMPILER_NAME=clang++ CXX=clang++ ARCH=x86 CXXFLAGS="-stdlib=libc++"
      addons:
        apt:
          packages:
            - libc++-dev:i386
            - libc6-dev-i386
            - linux-libc-dev:i386
            - libgcc-4.8-dev:i386

    - os: linux
      dist: trusty
      env: COMPILER_NAME=clang++ CXX=clang++ ARCH=x64 CXXFLAGS="-stdlib=libc++" 
      addons:
        apt:
          packages:
            - libc++-dev