# ref: https://stackoverflow.com/questions/35110123/travis-ci-with-c14-and-linux
language: generic
script: make

matrix:
  include:
    - os: linux
      dist: trusty    
      env: COMPILER_NAME=g++ CXX=g++-7 CC=gcc-7 CXXFLAGS="-m32"
      addons:
        apt:
          packages:
            - g++-7-multilib
            - linux-libc-dev:i386
          sources:
            - llvm-toolchain-precise-5.0
            - ubuntu-toolchain-r-test

    - os: linux
      dist: trusty    
      env: COMPILER_NAME=g++ CXX=g++-7 CC=gcc-7 CXXFLAGS="-m64"
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - llvm-toolchain-precise-5.0
            - ubuntu-toolchain-r-test
    
    - os: linux
      dist: trusty
      env: COMPILER_NAME=clang++ CXX=clang CC=clang CXXFLAGS="-m32 -stdlib=libc++"
            
    - os: linux
      dist: trusty    
      env: COMPILER_NAME=clang++ CXX=clang++ CC=clang CXXFLAGS="-m64 -stdlib=libc++"
