# ref: https://stackoverflow.com/questions/35110123/travis-ci-with-c14-and-linux
language: generic
script: make

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=g++ CXX=g++-7 CC=gcc-7 ARCH=x86
      addons:
        apt:
          packages:
            - g++-7-multilib
            - linux-libc-dev:i386
          sources:
            - llvm-toolchain-precise-5.0
            - ubuntu-toolchain-r-test

    - os: linux
      env: COMPILER_NAME=g++ CXX=g++-7 CC=gcc-7 ARCH=x64
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - llvm-toolchain-precise-5.0
            - ubuntu-toolchain-r-test
    
    - os: linux
      env: COMPILER_NAME=clang++ CXX=clang++-5.0 CC=clang-5.0 ARCH=x86 CXXFLAGS="-stdlib=libc++"
      addons:
        apt:
          packages:
            - clang-5.0
            - libc++-dev:i386
            - libc6-dev-i386
            - libgcc-4.9-dev:i386
            - linux-libc-dev:i386
          sources:
            - llvm-toolchain-precise-5.0
            - ubuntu-toolchain-r-test
            
    - os: linux
      env: COMPILER_NAME=clang++ CXX=clang++-5.0 CC=clang-5.0 ARCH=x64 CXXFLAGS="-stdlib=libc++" 
      addons:
        apt:
          packages:
            - clang-5.0
            - libc++-dev
          sources:
            - llvm-toolchain-precise-5.0
            - ubuntu-toolchain-r-test
