# ref: https://stackoverflow.com/questions/35110123/travis-ci-with-c14-and-linux
language: generic
script: make

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5 CXXFLAGS="-m32"
      addons:
        apt:
          packages:
            - g++-5-multilib
            - linux-libc-dev:i386
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test

    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5 CXXFLAGS="-m64"
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8 CXXFLAGS="-m32 -stdlib=libc++"
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev:i386
            - libc6-dev-i386
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8 CXXFLAGS="-m64 -stdlib=libc++"
      addons:
        apt:
          packages:
            - clang-3.8
            - libc++-dev
          sources:
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
